name: Build and Deploy

# on:
#   push:
#     branches:
#       - main
on: [pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      # Authenticate with GCP using service account key
      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"

      - name: Create instance template
        run: |
          gcloud compute instance-templates create webapp-instance-template-${{ steps.timestamp.outputs.timestamp }} \
            --machine-type=e2-medium \
            --network-tier=PREMIUM \
            --tags=webapp-route-tag \
            --region=us-east1 \
            --instance-template-region=us-east1 \
            --boot-disk-size=100GB \
            --boot-disk-type=pd-balanced \
            --image=centos-image-2024-04-03-15-50-31\
            --network-interface="network=cloud-test-vpc-5test,subnet=webapp5test,network-tier=PREMIUM" \
            --service-account= cloud-default-vpc-dev@fabled-equator-411703.iam.gserviceaccount.com \
            --scopes= https://www.googleapis.com/auth/cloud-platform \
            --metadata=startup-script="#!/bin/bash

            # content to overwrite .env file

            SCRIPT_CONTENT=\"
            HOST=10.0.2.3
            USER_NAME="webapp"
            PASSWORD=${password}
            DATABASE="webapp"
            PORT=8080
            \"

            echo \"\$SCRIPT_CONTENT\" | sudo tee /home/csye6225/webapp/webapp_develop/.env > /dev/null"

      
      