name: Integration testing

on: [pull_request]

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl enable mysql
          sudo systemctl start mysql
          sudo systemctl status mysql
          sudo mysql --user=root --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpassword'; FLUSH PRIVILEGES;"

      - name: Configure MySQL
        run: |
          sudo mysql --user=root --password=rootpassword --execute="CREATE DATABASE IF NOT EXISTS testdb;"

      - name: Install Dependencies
        run: npm install

      - name: Run Integration Tests
        run: npm run test:integration
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: rootpassword
          MYSQL_DB: testdb
