name: Integration testing
on: [pull_request]
jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install
    
    - name: Wait for Databases to be ready
      run: sleep 10

    - name: Run Integration Tests
      run: npm run test:integration
      env:
        MYSQL_HOST: mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: rootpassword
        MYSQL_DB: testdb